version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - secret-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
    env_file:
      - .env  
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - secret-network

volumes:
  redis_data:

networks:
  secret-network:
    driver: bridge